name: whatsapp_status
description: A WhatsApp Status/Story saver  app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  permission_handler: ^6.1.3
  fluttertoast: ^7.1.8
  video_compress: ^2.1.1
  provider: ^4.3.3
  share: ^2.0.0
  chewie: ^1.0.0
  path_provider: ^2.0.1
  path: ^1.8.0
  path_provider_ex: ^1.0.1
  shared_preferences: ^2.0.4
  photo_view: ^0.11.1
  google_fonts: ^2.0.0
  progress_indicators: ^0.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
